# Generated by Django 5.0.7 on 2024-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
