# Generated by Django 5.0.7 on 2024-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprestaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="address",),
        migrations.RemoveField(model_name="restaurant", name="phone_number",),
        migrations.RemoveField(model_name="restaurant", name="specialization",),
        migrations.RemoveField(model_name="restaurant", name="website",),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(default="No description provided", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(default="Location", max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(default="Nazev", max_length=100),
        ),
    ]
